TYPE=VIEW
query=select `sap_php`.`t_grpofg_header`.`id_grpofg_header` AS `id_grpofg_header`,`sap_php`.`t_grpofg_header`.`posting_date` AS `posting_date`,`sap_php`.`t_grpofg_header`.`do_no` AS `do_no`,`sap_php`.`t_grpofg_header`.`grpo_no` AS `grpo_no`,`sap_php`.`t_grpofg_header`.`grfg_no` AS `grfg_no`,`sap_php`.`t_grpofg_header`.`delivery_date` AS `delivery_date`,`sap_php`.`t_grpofg_header`.`plant` AS `plant`,`sap_php`.`t_grpofg_header`.`storage_location` AS `storage_location`,`sap_php`.`t_grpofg_header`.`item_group_code` AS `item_group_code`,`sap_php`.`t_grpofg_header`.`status` AS `status`,`sap_php`.`t_grpofg_detail`.`id_grpofg_h_detail` AS `id_grpofg_h_detail`,`sap_php`.`t_grpofg_detail`.`material_no` AS `material_no`,`sap_php`.`t_grpofg_detail`.`material_no_pos` AS `material_no_pos`,`sap_php`.`t_grpofg_detail`.`material_desc` AS `material_desc`,`sap_php`.`t_grpofg_detail`.`outstanding_qty` AS `outstanding_qty`,`sap_php`.`t_grpofg_detail`.`gr_quantity` AS `grpo_quantity`,`sap_php`.`t_grpofg_detail`.`grfg_quantity` AS `grfg_quantity`,`sap_php`.`t_grpofg_detail`.`uom` AS `uom`,`sap_php`.`t_grpofg_detail`.`item_storage_location` AS `item_storage_location` from (`sap_php`.`t_grpofg_header` join `sap_php`.`t_grpofg_detail` on((`sap_php`.`t_grpofg_header`.`id_grpofg_header` = `sap_php`.`t_grpofg_detail`.`id_grpofg_header`)))
md5=53299f5728eaafa51aad67e6a135f689
updatable=1
algorithm=0
definer_user=root
definer_host=localhost
suid=1
with_check_option=0
timestamp=2016-08-02 03:32:56
create-version=1
source=select `t_grpofg_header`.`id_grpofg_header` AS `id_grpofg_header`,`t_grpofg_header`.`posting_date` AS `posting_date`,`t_grpofg_header`.`do_no` AS `do_no`,`t_grpofg_header`.`grpo_no` AS `grpo_no`,`t_grpofg_header`.`grfg_no` AS `grfg_no`,`t_grpofg_header`.`delivery_date` AS `delivery_date`,`t_grpofg_header`.`plant` AS `plant`,`t_grpofg_header`.`storage_location` AS `storage_location`,`t_grpofg_header`.`item_group_code` AS `item_group_code`,`t_grpofg_header`.`status` AS `status`,`t_grpofg_detail`.`id_grpofg_h_detail` AS `id_grpofg_h_detail`,`t_grpofg_detail`.`material_no` AS `material_no`,`t_grpofg_detail`.`material_no_pos` AS `material_no_pos`,`t_grpofg_detail`.`material_desc` AS `material_desc`,`t_grpofg_detail`.`outstanding_qty` AS `outstanding_qty`,`t_grpofg_detail`.`gr_quantity` AS `grpo_quantity`,`t_grpofg_detail`.`grfg_quantity` AS `grfg_quantity`,`t_grpofg_detail`.`uom` AS `uom`,`t_grpofg_detail`.`item_storage_location` AS `item_storage_location` from (`t_grpofg_header` join `t_grpofg_detail` on((`t_grpofg_header`.`id_grpofg_header` = `t_grpofg_detail`.`id_grpofg_header`)))
client_cs_name=utf8
connection_cl_name=utf8_general_ci
view_body_utf8=select `sap_php`.`t_grpofg_header`.`id_grpofg_header` AS `id_grpofg_header`,`sap_php`.`t_grpofg_header`.`posting_date` AS `posting_date`,`sap_php`.`t_grpofg_header`.`do_no` AS `do_no`,`sap_php`.`t_grpofg_header`.`grpo_no` AS `grpo_no`,`sap_php`.`t_grpofg_header`.`grfg_no` AS `grfg_no`,`sap_php`.`t_grpofg_header`.`delivery_date` AS `delivery_date`,`sap_php`.`t_grpofg_header`.`plant` AS `plant`,`sap_php`.`t_grpofg_header`.`storage_location` AS `storage_location`,`sap_php`.`t_grpofg_header`.`item_group_code` AS `item_group_code`,`sap_php`.`t_grpofg_header`.`status` AS `status`,`sap_php`.`t_grpofg_detail`.`id_grpofg_h_detail` AS `id_grpofg_h_detail`,`sap_php`.`t_grpofg_detail`.`material_no` AS `material_no`,`sap_php`.`t_grpofg_detail`.`material_no_pos` AS `material_no_pos`,`sap_php`.`t_grpofg_detail`.`material_desc` AS `material_desc`,`sap_php`.`t_grpofg_detail`.`outstanding_qty` AS `outstanding_qty`,`sap_php`.`t_grpofg_detail`.`gr_quantity` AS `grpo_quantity`,`sap_php`.`t_grpofg_detail`.`grfg_quantity` AS `grfg_quantity`,`sap_php`.`t_grpofg_detail`.`uom` AS `uom`,`sap_php`.`t_grpofg_detail`.`item_storage_location` AS `item_storage_location` from (`sap_php`.`t_grpofg_header` join `sap_php`.`t_grpofg_detail` on((`sap_php`.`t_grpofg_header`.`id_grpofg_header` = `sap_php`.`t_grpofg_detail`.`id_grpofg_header`)))
