TYPE=VIEW
query=select `sap_php`.`t_stdstock_header`.`id_stdstock_header` AS `id_stdstock_header`,`sap_php`.`t_stdstock_header`.`pr_no` AS `pr_no`,`sap_php`.`t_stdstock_header`.`plant` AS `plant`,`sap_php`.`t_stdstock_header`.`storage_location` AS `storage_location`,`sap_php`.`t_stdstock_header`.`request_reason` AS `request_reason`,`sap_php`.`t_stdstock_header`.`item_group_code` AS `item_group_code`,`sap_php`.`t_stdstock_header`.`created_date` AS `created_date`,`sap_php`.`t_stdstock_header`.`status` AS `status`,`sap_php`.`t_stdstock_detail`.`id_stdstock_h_detail` AS `id_stdstock_h_detail`,`sap_php`.`t_stdstock_detail`.`material_no` AS `material_no`,`sap_php`.`t_stdstock_detail`.`material_desc` AS `material_desc`,`sap_php`.`t_stdstock_header`.`delivery_date` AS `delivery_date`,`sap_php`.`t_stdstock_detail`.`requirement_qty` AS `requirement_qty`,`sap_php`.`t_stdstock_detail`.`uom` AS `uom` from (`sap_php`.`t_stdstock_header` join `sap_php`.`t_stdstock_detail` on((`sap_php`.`t_stdstock_header`.`id_stdstock_header` = `sap_php`.`t_stdstock_detail`.`id_stdstock_header`)))
md5=72d449e6f4e1b941cde79d38f3d648be
updatable=1
algorithm=0
definer_user=root
definer_host=localhost
suid=1
with_check_option=0
timestamp=2016-08-02 03:32:56
create-version=1
source=select `t_stdstock_header`.`id_stdstock_header` AS `id_stdstock_header`,`t_stdstock_header`.`pr_no` AS `pr_no`,`t_stdstock_header`.`plant` AS `plant`,`t_stdstock_header`.`storage_location` AS `storage_location`,`t_stdstock_header`.`request_reason` AS `request_reason`,`t_stdstock_header`.`item_group_code` AS `item_group_code`,`t_stdstock_header`.`created_date` AS `created_date`,`t_stdstock_header`.`status` AS `status`,`t_stdstock_detail`.`id_stdstock_h_detail` AS `id_stdstock_h_detail`,`t_stdstock_detail`.`material_no` AS `material_no`,`t_stdstock_detail`.`material_desc` AS `material_desc`,`t_stdstock_header`.`delivery_date` AS `delivery_date`,`t_stdstock_detail`.`requirement_qty` AS `requirement_qty`,`t_stdstock_detail`.`uom` AS `uom` from (`t_stdstock_header` join `t_stdstock_detail` on((`t_stdstock_header`.`id_stdstock_header` = `t_stdstock_detail`.`id_stdstock_header`)))
client_cs_name=utf8
connection_cl_name=utf8_general_ci
view_body_utf8=select `sap_php`.`t_stdstock_header`.`id_stdstock_header` AS `id_stdstock_header`,`sap_php`.`t_stdstock_header`.`pr_no` AS `pr_no`,`sap_php`.`t_stdstock_header`.`plant` AS `plant`,`sap_php`.`t_stdstock_header`.`storage_location` AS `storage_location`,`sap_php`.`t_stdstock_header`.`request_reason` AS `request_reason`,`sap_php`.`t_stdstock_header`.`item_group_code` AS `item_group_code`,`sap_php`.`t_stdstock_header`.`created_date` AS `created_date`,`sap_php`.`t_stdstock_header`.`status` AS `status`,`sap_php`.`t_stdstock_detail`.`id_stdstock_h_detail` AS `id_stdstock_h_detail`,`sap_php`.`t_stdstock_detail`.`material_no` AS `material_no`,`sap_php`.`t_stdstock_detail`.`material_desc` AS `material_desc`,`sap_php`.`t_stdstock_header`.`delivery_date` AS `delivery_date`,`sap_php`.`t_stdstock_detail`.`requirement_qty` AS `requirement_qty`,`sap_php`.`t_stdstock_detail`.`uom` AS `uom` from (`sap_php`.`t_stdstock_header` join `sap_php`.`t_stdstock_detail` on((`sap_php`.`t_stdstock_header`.`id_stdstock_header` = `sap_php`.`t_stdstock_detail`.`id_stdstock_header`)))
