TYPE=VIEW
query=select `sap_php`.`t_stockoutlet_header`.`id_stockoutlet_header` AS `id_stockoutlet_header`,`sap_php`.`t_stockoutlet_header`.`posting_date` AS `posting_date`,`sap_php`.`t_stockoutlet_header`.`material_doc_no` AS `material_doc_no`,`sap_php`.`t_stockoutlet_header`.`plant` AS `plant`,`sap_php`.`t_stockoutlet_header`.`storage_location` AS `storage_location`,`sap_php`.`t_stockoutlet_header`.`item_group_code` AS `item_group_code`,`sap_php`.`t_stockoutlet_header`.`status` AS `status`,`sap_php`.`t_stockoutlet_detail`.`id_stockoutlet_h_detail` AS `id_stockoutlet_h_detail`,`sap_php`.`t_stockoutlet_detail`.`material_no` AS `material_no`,`sap_php`.`t_stockoutlet_detail`.`material_desc` AS `material_desc`,`sap_php`.`t_stockoutlet_detail`.`qty_gso` AS `qty_gso`,`sap_php`.`t_stockoutlet_detail`.`qty_gss` AS `qty_gss`,`sap_php`.`t_stockoutlet_detail`.`quantity` AS `quantity`,`sap_php`.`t_stockoutlet_detail`.`uom` AS `uom`,`sap_php`.`t_stockoutlet_detail_bom`.`material_no` AS `material_no_bom`,`sap_php`.`t_stockoutlet_detail_bom`.`material_desc` AS `material_desc_bom`,`sap_php`.`t_stockoutlet_detail_bom`.`quantity` AS `qty_bom`,`sap_php`.`t_stockoutlet_detail_bom`.`uom` AS `uom_bom` from ((`sap_php`.`t_stockoutlet_header` join `sap_php`.`t_stockoutlet_detail` on((`sap_php`.`t_stockoutlet_header`.`id_stockoutlet_header` = `sap_php`.`t_stockoutlet_detail`.`id_stockoutlet_header`))) left join `sap_php`.`t_stockoutlet_detail_bom` on((`sap_php`.`t_stockoutlet_detail_bom`.`id_stockoutlet_detail` = `sap_php`.`t_stockoutlet_detail`.`id_stockoutlet_detail`)))
md5=b458e9960940fd036f5bb5a65300310d
updatable=0
algorithm=0
definer_user=root
definer_host=localhost
suid=1
with_check_option=0
timestamp=2016-08-02 03:32:56
create-version=1
source=select `t_stockoutlet_header`.`id_stockoutlet_header` AS `id_stockoutlet_header`,`t_stockoutlet_header`.`posting_date` AS `posting_date`,`t_stockoutlet_header`.`material_doc_no` AS `material_doc_no`,`t_stockoutlet_header`.`plant` AS `plant`,`t_stockoutlet_header`.`storage_location` AS `storage_location`,`t_stockoutlet_header`.`item_group_code` AS `item_group_code`,`t_stockoutlet_header`.`status` AS `status`,`t_stockoutlet_detail`.`id_stockoutlet_h_detail` AS `id_stockoutlet_h_detail`,`t_stockoutlet_detail`.`material_no` AS `material_no`,`t_stockoutlet_detail`.`material_desc` AS `material_desc`,`t_stockoutlet_detail`.`qty_gso` AS `qty_gso`,`t_stockoutlet_detail`.`qty_gss` AS `qty_gss`,`t_stockoutlet_detail`.`quantity` AS `quantity`,`t_stockoutlet_detail`.`uom` AS `uom`,`t_stockoutlet_detail_bom`.`material_no` AS `material_no_bom`,`t_stockoutlet_detail_bom`.`material_desc` AS `material_desc_bom`,`t_stockoutlet_detail_bom`.`quantity` AS `qty_bom`,`t_stockoutlet_detail_bom`.`uom` AS `uom_bom` from ((`t_stockoutlet_header` join `t_stockoutlet_detail` on((`t_stockoutlet_header`.`id_stockoutlet_header` = `t_stockoutlet_detail`.`id_stockoutlet_header`))) left join `t_stockoutlet_detail_bom` on((`t_stockoutlet_detail_bom`.`id_stockoutlet_detail` = `t_stockoutlet_detail`.`id_stockoutlet_detail`)))
client_cs_name=utf8
connection_cl_name=utf8_general_ci
view_body_utf8=select `sap_php`.`t_stockoutlet_header`.`id_stockoutlet_header` AS `id_stockoutlet_header`,`sap_php`.`t_stockoutlet_header`.`posting_date` AS `posting_date`,`sap_php`.`t_stockoutlet_header`.`material_doc_no` AS `material_doc_no`,`sap_php`.`t_stockoutlet_header`.`plant` AS `plant`,`sap_php`.`t_stockoutlet_header`.`storage_location` AS `storage_location`,`sap_php`.`t_stockoutlet_header`.`item_group_code` AS `item_group_code`,`sap_php`.`t_stockoutlet_header`.`status` AS `status`,`sap_php`.`t_stockoutlet_detail`.`id_stockoutlet_h_detail` AS `id_stockoutlet_h_detail`,`sap_php`.`t_stockoutlet_detail`.`material_no` AS `material_no`,`sap_php`.`t_stockoutlet_detail`.`material_desc` AS `material_desc`,`sap_php`.`t_stockoutlet_detail`.`qty_gso` AS `qty_gso`,`sap_php`.`t_stockoutlet_detail`.`qty_gss` AS `qty_gss`,`sap_php`.`t_stockoutlet_detail`.`quantity` AS `quantity`,`sap_php`.`t_stockoutlet_detail`.`uom` AS `uom`,`sap_php`.`t_stockoutlet_detail_bom`.`material_no` AS `material_no_bom`,`sap_php`.`t_stockoutlet_detail_bom`.`material_desc` AS `material_desc_bom`,`sap_php`.`t_stockoutlet_detail_bom`.`quantity` AS `qty_bom`,`sap_php`.`t_stockoutlet_detail_bom`.`uom` AS `uom_bom` from ((`sap_php`.`t_stockoutlet_header` join `sap_php`.`t_stockoutlet_detail` on((`sap_php`.`t_stockoutlet_header`.`id_stockoutlet_header` = `sap_php`.`t_stockoutlet_detail`.`id_stockoutlet_header`))) left join `sap_php`.`t_stockoutlet_detail_bom` on((`sap_php`.`t_stockoutlet_detail_bom`.`id_stockoutlet_detail` = `sap_php`.`t_stockoutlet_detail`.`id_stockoutlet_detail`)))
