TYPE=VIEW
query=select `sap_php`.`t_stockoutlet_detail`.`id_stockoutlet_header` AS `id_stockoutlet_header`,`sap_php`.`t_stockoutlet_detail`.`material_no` AS `material_no`,`sap_php`.`t_stockoutlet_detail`.`uom` AS `uom`,sum(`sap_php`.`t_stockoutlet_detail`.`quantity`) AS `quantity` from `sap_php`.`t_stockoutlet_detail` where (not(`sap_php`.`t_stockoutlet_detail`.`id_stockoutlet_detail` in (select `sap_php`.`t_stockoutlet_detail_bom`.`id_stockoutlet_detail` AS `id_stockoutlet_detail` from `sap_php`.`t_stockoutlet_detail_bom` where ((`sap_php`.`t_stockoutlet_detail_bom`.`id_stockoutlet_header` = `sap_php`.`t_stockoutlet_detail`.`id_stockoutlet_header`) and (`sap_php`.`t_stockoutlet_detail_bom`.`id_stockoutlet_detail` = `sap_php`.`t_stockoutlet_detail`.`id_stockoutlet_detail`))))) group by `sap_php`.`t_stockoutlet_detail`.`id_stockoutlet_header`,`sap_php`.`t_stockoutlet_detail`.`material_no`,`sap_php`.`t_stockoutlet_detail`.`uom` union select `sap_php`.`t_stockoutlet_detail_bom`.`id_stockoutlet_header` AS `id_stockoutlet_header`,`sap_php`.`t_stockoutlet_detail_bom`.`material_no` AS `material_no`,`sap_php`.`t_stockoutlet_detail_bom`.`uom` AS `uom`,sum(`sap_php`.`t_stockoutlet_detail_bom`.`quantity`) AS `quantity` from `sap_php`.`t_stockoutlet_detail_bom` group by `sap_php`.`t_stockoutlet_detail_bom`.`id_stockoutlet_header`,`sap_php`.`t_stockoutlet_detail_bom`.`material_no`,`sap_php`.`t_stockoutlet_detail_bom`.`uom`
md5=9ef65233adef02f27b8e230ff43ba8c4
updatable=0
algorithm=0
definer_user=root
definer_host=192.168.143.77
suid=1
with_check_option=0
timestamp=2016-08-02 03:32:56
create-version=1
source=select `t_stockoutlet_detail`.`id_stockoutlet_header` AS `id_stockoutlet_header`,`t_stockoutlet_detail`.`material_no` AS `material_no`,`t_stockoutlet_detail`.`uom` AS `uom`,sum(`t_stockoutlet_detail`.`quantity`) AS `quantity` from `t_stockoutlet_detail` where (not(`t_stockoutlet_detail`.`id_stockoutlet_detail` in (select `t_stockoutlet_detail_bom`.`id_stockoutlet_detail` AS `id_stockoutlet_detail` from `t_stockoutlet_detail_bom` where ((`t_stockoutlet_detail_bom`.`id_stockoutlet_header` = `t_stockoutlet_detail`.`id_stockoutlet_header`) and (`t_stockoutlet_detail_bom`.`id_stockoutlet_detail` = `t_stockoutlet_detail`.`id_stockoutlet_detail`))))) group by `t_stockoutlet_detail`.`id_stockoutlet_header`,`t_stockoutlet_detail`.`material_no`,`t_stockoutlet_detail`.`uom` union select `t_stockoutlet_detail_bom`.`id_stockoutlet_header` AS `id_stockoutlet_header`,`t_stockoutlet_detail_bom`.`material_no` AS `material_no`,`t_stockoutlet_detail_bom`.`uom` AS `uom`,sum(`t_stockoutlet_detail_bom`.`quantity`) AS `quantity` from `t_stockoutlet_detail_bom` group by `t_stockoutlet_detail_bom`.`id_stockoutlet_header`,`t_stockoutlet_detail_bom`.`material_no`,`t_stockoutlet_detail_bom`.`uom`
client_cs_name=utf8
connection_cl_name=utf8_general_ci
view_body_utf8=select `sap_php`.`t_stockoutlet_detail`.`id_stockoutlet_header` AS `id_stockoutlet_header`,`sap_php`.`t_stockoutlet_detail`.`material_no` AS `material_no`,`sap_php`.`t_stockoutlet_detail`.`uom` AS `uom`,sum(`sap_php`.`t_stockoutlet_detail`.`quantity`) AS `quantity` from `sap_php`.`t_stockoutlet_detail` where (not(`sap_php`.`t_stockoutlet_detail`.`id_stockoutlet_detail` in (select `sap_php`.`t_stockoutlet_detail_bom`.`id_stockoutlet_detail` AS `id_stockoutlet_detail` from `sap_php`.`t_stockoutlet_detail_bom` where ((`sap_php`.`t_stockoutlet_detail_bom`.`id_stockoutlet_header` = `sap_php`.`t_stockoutlet_detail`.`id_stockoutlet_header`) and (`sap_php`.`t_stockoutlet_detail_bom`.`id_stockoutlet_detail` = `sap_php`.`t_stockoutlet_detail`.`id_stockoutlet_detail`))))) group by `sap_php`.`t_stockoutlet_detail`.`id_stockoutlet_header`,`sap_php`.`t_stockoutlet_detail`.`material_no`,`sap_php`.`t_stockoutlet_detail`.`uom` union select `sap_php`.`t_stockoutlet_detail_bom`.`id_stockoutlet_header` AS `id_stockoutlet_header`,`sap_php`.`t_stockoutlet_detail_bom`.`material_no` AS `material_no`,`sap_php`.`t_stockoutlet_detail_bom`.`uom` AS `uom`,sum(`sap_php`.`t_stockoutlet_detail_bom`.`quantity`) AS `quantity` from `sap_php`.`t_stockoutlet_detail_bom` group by `sap_php`.`t_stockoutlet_detail_bom`.`id_stockoutlet_header`,`sap_php`.`t_stockoutlet_detail_bom`.`material_no`,`sap_php`.`t_stockoutlet_detail_bom`.`uom`
