TYPE=VIEW
query=select `sap_php`.`t_grpodlv_header`.`id_grpodlv_header` AS `id_do_trans`,`sap_php`.`t_grpodlv_header`.`posting_date` AS `posting_date`,`sap_php`.`t_grpodlv_header`.`do_no` AS `do_no`,`sap_php`.`t_grpodlv_header`.`plant` AS `plant`,`sap_php`.`t_grpodlv_detail`.`material_no` AS `material_no`,`sap_php`.`t_grpodlv_detail`.`material_desc` AS `material_desc`,`sap_php`.`t_grpodlv_detail`.`uom` AS `uom`,sum((`sap_php`.`t_grpodlv_detail`.`gr_quantity` - coalesce(`sap_php`.`t_grpodlv_detail`.`tssck_qty`,0))) AS `quantity` from (`sap_php`.`t_grpodlv_header` join `sap_php`.`t_grpodlv_detail` on((`sap_php`.`t_grpodlv_detail`.`id_grpodlv_header` = `sap_php`.`t_grpodlv_header`.`id_grpodlv_header`))) where ((`sap_php`.`t_grpodlv_header`.`status` = 2) and ((`sap_php`.`t_grpodlv_detail`.`gr_quantity` - coalesce(`sap_php`.`t_grpodlv_detail`.`tssck_qty`,0)) > 0)) group by `sap_php`.`t_grpodlv_header`.`id_grpodlv_header`,`sap_php`.`t_grpodlv_header`.`posting_date`,`sap_php`.`t_grpodlv_header`.`do_no`,`sap_php`.`t_grpodlv_header`.`plant`,`sap_php`.`t_grpodlv_detail`.`material_no`,`sap_php`.`t_grpodlv_detail`.`uom`,`sap_php`.`t_grpodlv_detail`.`material_desc`
md5=6a3a47fd1a03649bd52647e68edc07f0
updatable=0
algorithm=0
definer_user=root
definer_host=localhost
suid=1
with_check_option=0
timestamp=2016-12-03 06:57:34
create-version=1
source=SELECT \n        `sap_php`.`t_grpodlv_header`.`id_grpodlv_header` AS `id_do_trans`,\n        `sap_php`.`t_grpodlv_header`.`posting_date` AS `posting_date`,\n        `sap_php`.`t_grpodlv_header`.`do_no` AS `do_no`,\n        `sap_php`.`t_grpodlv_header`.`plant` AS `plant`,\n        `sap_php`.`t_grpodlv_detail`.`material_no` AS `material_no`,\n        `sap_php`.`t_grpodlv_detail`.`material_desc` AS `material_desc`,\n        `sap_php`.`t_grpodlv_detail`.`uom` AS `uom`,\n        SUM((`sap_php`.`t_grpodlv_detail`.`gr_quantity` - COALESCE(`sap_php`.`t_grpodlv_detail`.`tssck_qty`,\n                0))) AS `quantity`\n    FROM\n        (`t_grpodlv_header`\n        JOIN `t_grpodlv_detail` ON ((`sap_php`.`t_grpodlv_detail`.`id_grpodlv_header` = `sap_php`.`t_grpodlv_header`.`id_grpodlv_header`)))\n    WHERE\n        ((`sap_php`.`t_grpodlv_header`.`status` = 2)\n            AND ((`sap_php`.`t_grpodlv_detail`.`gr_quantity` - COALESCE(`sap_php`.`t_grpodlv_detail`.`tssck_qty`,\n                0)) > 0))\n    GROUP BY `sap_php`.`t_grpodlv_header`.`id_grpodlv_header` , `sap_php`.`t_grpodlv_header`.`posting_date` , `sap_php`.`t_grpodlv_header`.`do_no` , `sap_php`.`t_grpodlv_header`.`plant` , `sap_php`.`t_grpodlv_detail`.`material_no` , `sap_php`.`t_grpodlv_detail`.`uom` , `sap_php`.`t_grpodlv_detail`.`material_desc`
client_cs_name=utf8
connection_cl_name=utf8_general_ci
view_body_utf8=select `sap_php`.`t_grpodlv_header`.`id_grpodlv_header` AS `id_do_trans`,`sap_php`.`t_grpodlv_header`.`posting_date` AS `posting_date`,`sap_php`.`t_grpodlv_header`.`do_no` AS `do_no`,`sap_php`.`t_grpodlv_header`.`plant` AS `plant`,`sap_php`.`t_grpodlv_detail`.`material_no` AS `material_no`,`sap_php`.`t_grpodlv_detail`.`material_desc` AS `material_desc`,`sap_php`.`t_grpodlv_detail`.`uom` AS `uom`,sum((`sap_php`.`t_grpodlv_detail`.`gr_quantity` - coalesce(`sap_php`.`t_grpodlv_detail`.`tssck_qty`,0))) AS `quantity` from (`sap_php`.`t_grpodlv_header` join `sap_php`.`t_grpodlv_detail` on((`sap_php`.`t_grpodlv_detail`.`id_grpodlv_header` = `sap_php`.`t_grpodlv_header`.`id_grpodlv_header`))) where ((`sap_php`.`t_grpodlv_header`.`status` = 2) and ((`sap_php`.`t_grpodlv_detail`.`gr_quantity` - coalesce(`sap_php`.`t_grpodlv_detail`.`tssck_qty`,0)) > 0)) group by `sap_php`.`t_grpodlv_header`.`id_grpodlv_header`,`sap_php`.`t_grpodlv_header`.`posting_date`,`sap_php`.`t_grpodlv_header`.`do_no`,`sap_php`.`t_grpodlv_header`.`plant`,`sap_php`.`t_grpodlv_detail`.`material_no`,`sap_php`.`t_grpodlv_detail`.`uom`,`sap_php`.`t_grpodlv_detail`.`material_desc`
