TYPE=VIEW
query=select `sap_php`.`t_waste_detail`.`id_waste_header` AS `id_waste_header`,`sap_php`.`t_waste_detail`.`material_no` AS `material_no`,`sap_php`.`t_waste_detail`.`uom` AS `uom`,sum(`sap_php`.`t_waste_detail`.`quantity`) AS `quantity` from `sap_php`.`t_waste_detail` where (not(`sap_php`.`t_waste_detail`.`id_waste_detail` in (select `sap_php`.`t_waste_detail_bom`.`id_waste_detail` AS `id_waste_detail` from `sap_php`.`t_waste_detail_bom` where ((`sap_php`.`t_waste_detail_bom`.`material_no_sfg` = `sap_php`.`t_waste_detail`.`material_no`) and (`sap_php`.`t_waste_detail_bom`.`id_waste_header` = `sap_php`.`t_waste_detail`.`id_waste_header`) and (`sap_php`.`t_waste_detail_bom`.`id_waste_detail` = `sap_php`.`t_waste_detail`.`id_waste_detail`))))) group by `sap_php`.`t_waste_detail`.`id_waste_header`,`sap_php`.`t_waste_detail`.`material_no`,`sap_php`.`t_waste_detail`.`uom` union select `sap_php`.`t_waste_detail_bom`.`id_waste_header` AS `id_waste_header`,`sap_php`.`t_waste_detail_bom`.`material_no` AS `material_no`,`sap_php`.`t_waste_detail_bom`.`uom` AS `uom`,sum(`sap_php`.`t_waste_detail_bom`.`quantity`) AS `quantity` from `sap_php`.`t_waste_detail_bom` group by `sap_php`.`t_waste_detail_bom`.`id_waste_header`,`sap_php`.`t_waste_detail_bom`.`material_no`,`sap_php`.`t_waste_detail_bom`.`uom`
md5=af0bf052d7e60cdf35546da17b99f16a
updatable=0
algorithm=0
definer_user=root
definer_host=localhost
suid=1
with_check_option=0
timestamp=2016-08-02 03:32:56
create-version=1
source=select `t_waste_detail`.`id_waste_header` AS `id_waste_header`,`t_waste_detail`.`material_no` AS `material_no`,`t_waste_detail`.`uom` AS `uom`,sum(`t_waste_detail`.`quantity`) AS `quantity` from `t_waste_detail` where (not(`t_waste_detail`.`id_waste_detail` in (select `t_waste_detail_bom`.`id_waste_detail` AS `id_waste_detail` from `t_waste_detail_bom` where ((`t_waste_detail_bom`.`material_no_sfg` = `t_waste_detail`.`material_no`) and (`t_waste_detail_bom`.`id_waste_header` = `t_waste_detail`.`id_waste_header`) and (`t_waste_detail_bom`.`id_waste_detail` = `t_waste_detail`.`id_waste_detail`))))) group by `t_waste_detail`.`id_waste_header`,`t_waste_detail`.`material_no`,`t_waste_detail`.`uom` union select `t_waste_detail_bom`.`id_waste_header` AS `id_waste_header`,`t_waste_detail_bom`.`material_no` AS `material_no`,`t_waste_detail_bom`.`uom` AS `uom`,sum(`t_waste_detail_bom`.`quantity`) AS `quantity` from `t_waste_detail_bom` group by `t_waste_detail_bom`.`id_waste_header`,`t_waste_detail_bom`.`material_no`,`t_waste_detail_bom`.`uom`
client_cs_name=utf8
connection_cl_name=utf8_general_ci
view_body_utf8=select `sap_php`.`t_waste_detail`.`id_waste_header` AS `id_waste_header`,`sap_php`.`t_waste_detail`.`material_no` AS `material_no`,`sap_php`.`t_waste_detail`.`uom` AS `uom`,sum(`sap_php`.`t_waste_detail`.`quantity`) AS `quantity` from `sap_php`.`t_waste_detail` where (not(`sap_php`.`t_waste_detail`.`id_waste_detail` in (select `sap_php`.`t_waste_detail_bom`.`id_waste_detail` AS `id_waste_detail` from `sap_php`.`t_waste_detail_bom` where ((`sap_php`.`t_waste_detail_bom`.`material_no_sfg` = `sap_php`.`t_waste_detail`.`material_no`) and (`sap_php`.`t_waste_detail_bom`.`id_waste_header` = `sap_php`.`t_waste_detail`.`id_waste_header`) and (`sap_php`.`t_waste_detail_bom`.`id_waste_detail` = `sap_php`.`t_waste_detail`.`id_waste_detail`))))) group by `sap_php`.`t_waste_detail`.`id_waste_header`,`sap_php`.`t_waste_detail`.`material_no`,`sap_php`.`t_waste_detail`.`uom` union select `sap_php`.`t_waste_detail_bom`.`id_waste_header` AS `id_waste_header`,`sap_php`.`t_waste_detail_bom`.`material_no` AS `material_no`,`sap_php`.`t_waste_detail_bom`.`uom` AS `uom`,sum(`sap_php`.`t_waste_detail_bom`.`quantity`) AS `quantity` from `sap_php`.`t_waste_detail_bom` group by `sap_php`.`t_waste_detail_bom`.`id_waste_header`,`sap_php`.`t_waste_detail_bom`.`material_no`,`sap_php`.`t_waste_detail_bom`.`uom`
