TYPE=VIEW
query=select `sap_php`.`t_waste_header`.`id_waste_header` AS `id_waste_header`,`sap_php`.`t_waste_header`.`posting_date` AS `posting_date`,`sap_php`.`t_waste_header`.`material_doc_no` AS `material_doc_no`,`sap_php`.`t_waste_header`.`plant` AS `plant`,`sap_php`.`t_waste_header`.`storage_location` AS `storage_location`,`sap_php`.`t_waste_header`.`item_group_code` AS `item_group_code`,`sap_php`.`t_waste_header`.`status` AS `status`,`sap_php`.`t_waste_detail`.`id_waste_h_detail` AS `id_waste_h_detail`,`sap_php`.`t_waste_detail`.`material_no` AS `material_no`,`sap_php`.`t_waste_detail`.`material_desc` AS `material_desc`,`sap_php`.`t_waste_detail`.`quantity` AS `quantity`,`sap_php`.`t_waste_detail`.`uom` AS `uom`,`sap_php`.`t_waste_detail`.`reason_name` AS `reason_name`,`sap_php`.`t_waste_detail`.`other_reason` AS `other_reason`,`sap_php`.`t_waste_detail_bom`.`material_no` AS `material_no_bom`,`sap_php`.`t_waste_detail_bom`.`material_desc` AS `material_desc_bom`,`sap_php`.`t_waste_detail_bom`.`quantity` AS `qty_bom`,`sap_php`.`t_waste_detail_bom`.`uom` AS `uom_bom` from ((`sap_php`.`t_waste_header` join `sap_php`.`t_waste_detail` on((`sap_php`.`t_waste_header`.`id_waste_header` = `sap_php`.`t_waste_detail`.`id_waste_header`))) left join `sap_php`.`t_waste_detail_bom` on((`sap_php`.`t_waste_detail_bom`.`id_waste_detail` = `sap_php`.`t_waste_detail`.`id_waste_detail`)))
md5=91141f00adb989f5c58eaaf64d57fbb6
updatable=0
algorithm=0
definer_user=root
definer_host=localhost
suid=1
with_check_option=0
timestamp=2016-08-02 03:32:56
create-version=1
source=select `t_waste_header`.`id_waste_header` AS `id_waste_header`,`t_waste_header`.`posting_date` AS `posting_date`,`t_waste_header`.`material_doc_no` AS `material_doc_no`,`t_waste_header`.`plant` AS `plant`,`t_waste_header`.`storage_location` AS `storage_location`,`t_waste_header`.`item_group_code` AS `item_group_code`,`t_waste_header`.`status` AS `status`,`t_waste_detail`.`id_waste_h_detail` AS `id_waste_h_detail`,`t_waste_detail`.`material_no` AS `material_no`,`t_waste_detail`.`material_desc` AS `material_desc`,`t_waste_detail`.`quantity` AS `quantity`,`t_waste_detail`.`uom` AS `uom`,`t_waste_detail`.`reason_name` AS `reason_name`,`t_waste_detail`.`other_reason` AS `other_reason`,`t_waste_detail_bom`.`material_no` AS `material_no_bom`,`t_waste_detail_bom`.`material_desc` AS `material_desc_bom`,`t_waste_detail_bom`.`quantity` AS `qty_bom`,`t_waste_detail_bom`.`uom` AS `uom_bom` from ((`t_waste_header` join `t_waste_detail` on((`t_waste_header`.`id_waste_header` = `t_waste_detail`.`id_waste_header`))) left join `t_waste_detail_bom` on((`t_waste_detail_bom`.`id_waste_detail` = `t_waste_detail`.`id_waste_detail`)))
client_cs_name=utf8
connection_cl_name=utf8_general_ci
view_body_utf8=select `sap_php`.`t_waste_header`.`id_waste_header` AS `id_waste_header`,`sap_php`.`t_waste_header`.`posting_date` AS `posting_date`,`sap_php`.`t_waste_header`.`material_doc_no` AS `material_doc_no`,`sap_php`.`t_waste_header`.`plant` AS `plant`,`sap_php`.`t_waste_header`.`storage_location` AS `storage_location`,`sap_php`.`t_waste_header`.`item_group_code` AS `item_group_code`,`sap_php`.`t_waste_header`.`status` AS `status`,`sap_php`.`t_waste_detail`.`id_waste_h_detail` AS `id_waste_h_detail`,`sap_php`.`t_waste_detail`.`material_no` AS `material_no`,`sap_php`.`t_waste_detail`.`material_desc` AS `material_desc`,`sap_php`.`t_waste_detail`.`quantity` AS `quantity`,`sap_php`.`t_waste_detail`.`uom` AS `uom`,`sap_php`.`t_waste_detail`.`reason_name` AS `reason_name`,`sap_php`.`t_waste_detail`.`other_reason` AS `other_reason`,`sap_php`.`t_waste_detail_bom`.`material_no` AS `material_no_bom`,`sap_php`.`t_waste_detail_bom`.`material_desc` AS `material_desc_bom`,`sap_php`.`t_waste_detail_bom`.`quantity` AS `qty_bom`,`sap_php`.`t_waste_detail_bom`.`uom` AS `uom_bom` from ((`sap_php`.`t_waste_header` join `sap_php`.`t_waste_detail` on((`sap_php`.`t_waste_header`.`id_waste_header` = `sap_php`.`t_waste_detail`.`id_waste_header`))) left join `sap_php`.`t_waste_detail_bom` on((`sap_php`.`t_waste_detail_bom`.`id_waste_detail` = `sap_php`.`t_waste_detail`.`id_waste_detail`)))
